DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS PRODUTO;

CREATE TABLE USUARIO (
    IDCONTAUSUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(500),
    SOBRENOME VARCHAR(500),
    CPF VARCHAR(500),
    EMAIL VARCHAR(500),
    SENHA VARCHAR(500),
    ENDERECO VARCHAR(500)
);

CREATE TABLE EMPRESA (
    IDEMPRESA INT AUTO_INCREMENT PRIMARY KEY,
    SENHA VARCHAR(500),
    EMAIL VARCHAR(500),
    ENDERECO VARCHAR(500),
    CNPJ VARCHAR(500),
    NOMEEMPRESA VARCHAR(500)
);

CREATE TABLE PRODUTO (
    IDPRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    PESO INT,
    DESCRICAO VARCHAR(5000),
    MATERIAL VARCHAR(1000)
);