DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS PRODUTO;

CREATE TABLE USUARIO (
    IDCONTAUSUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(20),
    SOBRENOME VARCHAR(30),
    CPF VARCHAR(11),
    EMAIL VARCHAR(40),
    SENHA VARCHAR(20),
    ENDERECO VARCHAR(60)
);

CREATE TABLE EMPRESA (
    IDEMPRESA INT AUTO_INCREMENT PRIMARY KEY,
    SENHA VARCHAR(20),
    EMAIL VARCHAR(40),
    ENDERECO VARCHAR(60),
    CNPJ VARCHAR(14),
    NOMEEMPRESA VARCHAR(30)
);

CREATE TABLE PRODUTO (
    IDPRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    PESO INT,
    DESCRICAO VARCHAR(150),
    MATERIAL VARCHAR(15)
);